version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  indexer:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python -m src.data_processing.index_processed_files

  lint:
    build: .
    volumes:
      - .:/app
    command: flake8 src/ tests/

networks:
  default:
    name: sparenergi_network