version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./static:/app/static

  indexer:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python -m src.data_processing.index_processed_files

  delete_vectors:
    build: .
    env_file:
      - .env
    command: python -m src.data_processing.delete_all_vectors

  test:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python tests/real_content_test.py