services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  lint:
    build: .
    volumes:
      - .:/app
    command: flake8 src/ tests/

networks:
  default:
    name: sparenergi_network